### ISSUE TITLE
Additional documentation for the badger-library

### ISSUE THREAD

**Issue by rmh78** [nasys/badgerboard#8]
Do you plan additional documentation for all the methods in the badger library, perhaps with sample-code? For now it is hard to get an overview about all implemented library-features without reading the whole source-code.

**Comment by KertIlm** [comment]
Hi, 

Added a [new file](https://github.com/nasys/badgerboard/blob/master/BadgerboardFunctions.md) documenting badgerboard functions

**Comment by rmh78** [comment]
Thanks a lot!
